export const strings = {
  en: {
    ACTIONS: 'Actions',
    ADD: 'Add',
    ADD_LIST: 'Add list',
    APP_AVAILABLE: 'App is available for offline use',
    CHECK: 'Check',
    CLOSE_EDIT: 'Close edit',
    CONFIRM_DELETE_ITEM: 'Are you sure you want to delete this item?',
    CONFIRM_DELETE_LIST: 'Are you sure you want to delete this list?',
    COPIED: 'Copied',
    COPY_NAME: 'Copy',
    COPY_TO_CLIPBOARD: 'Copy to clipboard',
    DELETE: 'Delete',
    DELETE_ITEM: 'Delete item',
    DELETE_LIST: 'Delete list',
    DISMISS: 'Dismiss',
    EDIT: 'Edit',
    EDIT_ITEM_NAME: 'Edit item name',
    EDIT_TITLE: 'Edit title',
    HIDE_LISTS: 'Hide lists',
    ITEM_NAME: 'Item name',
    LIST_TITLE: 'List title',
    NEW_CONTENT: 'New content is available and will be used when all tabs for this page are closed',
    NO_ITEMS: 'No items',
    NO_LIST_FOUND: 'No lists found',
    NO_TITLE: '<No title>',
    SAVE: 'Save',
    SHOW_LISTS: 'Show lists',
    TOGGLE_MENU: 'Toggle menu',
    UNCHECK: 'Uncheck',
  },
  sk: {
    ACTIONS: 'Akcie',
    ADD: 'Pridať',
    ADD_LIST: 'Pridať zoznam',
    APP_AVAILABLE: 'Aplikácia je pripravená na offline používanie',
    CHECK: 'Zaškrtnúť',
    CLOSE_EDIT: 'Zrušiť zmeny',
    CONFIRM_DELETE_ITEM: 'Skutočne chcete vymazať túto položku?',
    CONFIRM_DELETE_LIST: 'Skutočne chcete vymazať tento zoznam?',
    COPIED: 'Skopírované',
    COPY_NAME: 'Kopírovať',
    COPY_TO_CLIPBOARD: 'Kopírovať do schránky',
    DELETE: 'Vymazať',
    DELETE_ITEM: 'Vymazať položku',
    DELETE_LIST: 'Vymazať zoznam',
    DISMISS: 'Zavrieť',
    EDIT: 'Upraviť',
    EDIT_ITEM_NAME: 'Upraviť názov položky',
    EDIT_TITLE: 'Upraviť názov zoznamu',
    HIDE_LISTS: 'Zavrieť zoznamy',
    ITEM_NAME: 'Názov položky',
    LIST_TITLE: 'Názov zoznamu',
    NEW_CONTENT: 'Je dostupný nový obsah a bude použitý po zavretí všetkých kariet tejto stránky',
    NO_ITEMS: 'Žiadne položky',
    NO_LIST_FOUND: 'Žiadne zoznamy',
    NO_TITLE: '<Bez názvu>',
    SAVE: 'Uložiť',
    SHOW_LISTS: 'Zobraziť zoznamy',
    TOGGLE_MENU: 'Prepnúť menu',
    UNCHECK: 'Odškrtnúť',
  },
} as const;

type Language = 'en' | 'sk';

export type Translations = (typeof strings)[Language];
